### ISSUE TITLE
How do I use it with inputmethodService?

### ISSUE THREAD

**Issue by DineshNeupane** [Aghajari/AXEmojiView#1]
How do I use it with android softkeyboard inputmethodservice as a popup?

**Comment by Aghajari** [comment]
Hi,
What are you looking for exactly ?
see the app, everything exists already!

and simply you can use AXEmojiPopup, it will handle everything :)

> Basic Usage :
> ```java
> AXEmojiPopup emojiPopup = new AXEmojiPopup(emojiView);
> 
> emojiPopup.toggle(); // Toggles visibility of the Popup.
> emojiPopup.show(); // Shows the Popup.
> emojiPopup.dismiss(); // Dismisses the Popup.
> emojiPopup.isShowing(); // Returns true when Popup is showing.
> ```

**Comment by Aghajari** [comment]
Hi,
What are you looking for exactly ?
see the app, everything exists already!

and simply you can use AXEmojiPopup, it will handle everything :)

> Basic Usage :
> ```java
> AXEmojiPopup emojiPopup = new AXEmojiPopup(emojiView);
> 
> emojiPopup.toggle(); // Toggles visibility of the Popup.
> emojiPopup.show(); // Shows the Popup.
> emojiPopup.dismiss(); // Dismisses the Popup.
> emojiPopup.isShowing(); // Returns true when Popup is showing.
> ```

**Comment by Aghajari** [comment]
Hi,
What are you looking for exactly ?
see the app, everything exists already!

and simply you can use AXEmojiPopup, it will handle everything :)

> Basic Usage :
> ```java
> AXEmojiPopup emojiPopup = new AXEmojiPopup(emojiView);
> 
> emojiPopup.toggle(); // Toggles visibility of the Popup.
> emojiPopup.show(); // Shows the Popup.
> emojiPopup.dismiss(); // Dismisses the Popup.
> emojiPopup.isShowing(); // Returns true when Popup is showing.
> ```

**Comment by Aghajari** [comment]
Hi,
What are you looking for exactly ?
see the app, everything exists already!

and simply you can use AXEmojiPopup, it will handle everything :)

> Basic Usage :
> ```java
> AXEmojiPopup emojiPopup = new AXEmojiPopup(emojiView);
> 
> emojiPopup.toggle(); // Toggles visibility of the Popup.
> emojiPopup.show(); // Shows the Popup.
> emojiPopup.dismiss(); // Dismisses the Popup.
> emojiPopup.isShowing(); // Returns true when Popup is showing.
> ```

**Comment by hsinha76** [comment]
@DineshNeupane Any update if you have achieved it?
