### ISSUE TITLE
Please publish the project to MavenCentral or maven.google.com

### ISSUE THREAD

**Issue by hallisonoliveira** [Aghajari/AXEmojiView#10]
Hello @Aghajari, could you please publish the project to maven central? I'm trying to remove jcenter() and your library is still not available on mavenCentral() or google().

Thanks!

**Comment by Aghajari** [comment]
hi,
You can use this instead of jcenter : 
```gradle
        maven {
            url 'https://dl.bintray.com/Aghajari/maven' 
        }
```

**Comment by hallisonoliveira** [comment]
I'm getting 403 Forbiden from that: 

`Could not HEAD 'https://dl.bintray.com/Aghajari/maven/com/aghajari/emojiview/AXEmojiView/1.3.0/AXEmojiView-1.3.0.pom'. Received status code 403 from server: Forbidden`

I don't know if there is another solution or if that is a problem on binary.

**Comment by Aghajari** [comment]
Yeh, seems like bintray has been stopped.
i'll check it soon. You can use the 

You can use this for now..

[AXEmojiView-release.aar.zip](https://github.com/Aghajari/AXEmojiView/files/6422219/AXEmojiView-release.aar.zip)

**Comment by hallisonoliveira** [comment]
Ok, thank you for the support.

**Comment by Aghajari** [comment]
AXEmojiView is available in `mavenCentral()` now!
