### ISSUE TITLE
Overlapping Emoji on New Line as Emoji Size increases

### ISSUE THREAD

**Issue by LutherLee** [Aghajari/AXEmojiView#14]
When textview's textSize = "16sp" and emojiSize = "24dp", there is overlapping between emoji on new line (>1 line).

See picture below:
![IMG_20210602_234201](https://user-images.githubusercontent.com/31267492/120510733-49aa3b00-c3fc-11eb-9c6c-210252a28825.jpg)

**Comment by aliusman** [comment]
I just tried that on my dev, I dont see any overlaps 
![image](https://user-images.githubusercontent.com/5491814/120891662-e2cd9180-c648-11eb-8c11-ad8fe6d15afb.png)

**Comment by Aghajari** [comment]
Hi, 24dp is much larger than 16sp, try 18dp for emoji size or 22sp for TextSize
