### ISSUE TITLE
EditText Loses Focus After Clicking Keyboard's ImeOptions of AXEmojiSearchView

### ISSUE THREAD

**Issue by LutherLee** [Aghajari/AXEmojiView#15]
<ins>**Steps to reproduce:**</ins>
1) Click on ***AXEmojiSearchView*** button (the layout is shown with the keyboard)
2) Press the ImeOptions / action button of the keyboard    

<ins>**Expected behaviour:**</ins>
**AXEmojiSearchView** is closed and **EditText** regains / retains focus

<ins>**Current behaviour:**</ins>
**AXEmojiSearchView** is closed but **EditText** loses focus

**Comment by Aghajari** [comment]
Hi, thanks

Fixed on v1.4.0
