### ISSUE TITLE
Instructions missing on how to update emojis

### ISSUE THREAD

**Issue by vonox7** [Aghajari/AXEmojiView#19]
AXEmojiView currently uses [Emoji 12.1](https://emojipedia.org/emoji-12.1/) (released on 2019-10-29). 
Emoji 13.0 and Emoji 13.1 (released on major platforms in 2020 and 2021) are both missing in AXEmojiView.

It would be helpful to have in the Readme instructions how to update the emoji database to the new set of emojis to allow the community to create PRs with for Emoji updates. (and possibly update it to Emoji 13.1)

**Comment by Aghajari** [comment]
Hey, Thats a great idea,
Sure i'll do that as soon as it's possible.

**Comment by Aghajari** [comment]
Done

**Comment by Aghajari** [comment]
Hi @vonox7, you can see [commit changes](https://github.com/Aghajari/AXEmojiView/commit/0e32210de26c6c430ba70a5c6194915d7ab799a9)
just updated the emoji icons from tg, 

I'm waiting for new Microsoft fluent emoji set ([Read more](https://blog.emojipedia.org/new-fluent-emoji-designs-from-microsoft/)), i'll add a new EmojiProvider for this design to AXEmojiView as soon as a stable version is released and i'll share the instructions with it, (Maybe with the release of a new tool for auto-updating emoji from [emojipedia.org](https://emojipedia.org))

**Comment by vonox7** [comment]
Did i understand your message correctly that you used the files listed in https://github.com/DrKLO/Telegram/tree/master/TMessagesProj/src/main/assets/emoji ?
