### ISSUE TITLE
Not working on Chromebook

### ISSUE THREAD

**Issue by Janneman84** [Aghajari/AXEmojiView#20]
I'd like to run my app on Chromebooks. I tried your demo project and when I press the smiley nothing happens. It probably has to do with Chromebooks having a hardware keyboard, so there is no soft keyboard, hence no place for the emojis to go to.

I just connected my Bluetooth keyboard from my old iMac to my phone. The emojis don't show here either, so hardware keyboards is definitely the problem.

**Comment by Aghajari** [comment]
Hi,
Use `AXEmojiPopupLayout` and call `updateKeyboardStateOpened(KeyboardHeight)`
this will ignore hardware keyboard height

**Comment by Janneman84** [comment]
Thank you that seems to work well. I have a few more questions but those are for later.
