### ISSUE TITLE
AXEmojiUtils.replaceWithEmojis not respecting emoji size ?

### ISSUE THREAD

**Issue by eemi2010** [Aghajari/AXEmojiView#21]
I m setting the size to 100 but the emojis stay small. What m I doing wrong ?

**Comment by Aghajari** [comment]
Hi @eemi2010 , 
Can you share your code? 
Did you set EmojiSize on the TextView?

**Comment by eemi2010** [comment]
I m trying to replace  emojis in a string with images. So I use AXEmojiUtils.replaceWithEmojis(text, 120); But the emojis are not 120dp wide. Maybe I m doing something wrong? Do I need to set the EmojiSize on the textview(Note that this is a regular TextView)? If yes please can you tell me how ? I could not see the API.

**Comment by eemi2010** [comment]
Ah I see there com.aghajari.emojiview.view.AXEmojiTextView I will test that one and come back to you.

**Comment by eemi2010** [comment]
Thank you. com.aghajari.emojiview.view.AXEmojiTextView seems to be working. Closing.
