### ISSUE TITLE
Expand to full screen

### ISSUE THREAD

**Issue by dbreskvar** [Aghajari/AXEmojiView#34]
Is it possible to expand the `AXEmojiPopupLayout` to have a height of the display screen? In case I would want it to be a standalone component? Or to display it above the edit text itself?

**Comment by Aghajari** [comment]
Hello @dbreskvar ,
Do not use `AXEmojiPopupLayout` here.
Just add `AXEmojiView` (or the pager) as a normal view to your activity without using popup.

**Comment by dbreskvar** [comment]
@Aghajari this works perfect! Just one more question. Is it possible to anchor the pager tabs to be persisted at the top when scrolling up? I might be missing something 🤞

**Comment by Aghajari** [comment]
Hello @dbreskvar 
What do you mean by pages? Emoji category?

**Comment by dbreskvar** [comment]
Yes, the categories get scrolled as well. This is the screenshot.
<img height="500" alt="image" src="https://user-images.githubusercontent.com/2612560/192720879-e604fbc0-6e10-405b-99c8-804147c073c1.png"/> 
And I'd like them to stay pinned at the top. They do come down when I fling scroll down but is it possible to always keep them at the top?
<img height="500" alt="image" src="https://user-images.githubusercontent.com/2612560/192721295-5cd05ce1-a189-4f28-99b7-7913cf6296dd.png"/>

**Comment by Aghajari** [comment]
@dbreskvar Try this code `disableEmojiViewCategoryParallax(emojiView);` just after creating the view.

```java
    public static void disableEmojiViewCategoryParallax(AXSingleEmojiView emojiView) {
        try {
            Field field = emojiView.getClass().getDeclaredField("scrollListener2");
            field.setAccessible(true);
            //noinspection ConstantConditions
            emojiView.getRecyclerView().removeOnScrollListener(
                    (RecyclerView.OnScrollListener) field.get(emojiView));
        } catch (Exception ignore) {
        }
    }
```

**Comment by dbreskvar** [comment]
Works like a charm! Thank you!
