### ISSUE TITLE
EmojiPopupLayout with AXSingleEmojiView fails to calculate height

### ISSUE THREAD

**Issue by dbreskvar** [Aghajari/AXEmojiView#35]
When you try to instantiate a view of `AXSingleEmojiView` it fails if keyboard hasn't been opened yet.
This is my code:
```
binding.emojiPopupLayout.initPopupView(
    AXSingleEmojiView(requireContext()).apply {
        editText = binding.emojiEditText
        onEmojiActionsListener = this
    }
)
binding.emojiPopupLayout.show()
```
If the keyboard is not open, the height is calculated wrong and the layout has 48dp of height (approximately).
After opening the keyboard and calling this function, it works well. I think this issue could also give support to a custom height defined by user and/or make it expandable through the whole view/screen.

**Comment by Aghajari** [comment]
Hello @dbreskvar , 
Are you trying to use EmojiPopupLayout  as a stand alone view?

**Comment by dbreskvar** [comment]
@Aghajari I've used it in a bottom sheet dialog but yes, it's technically a standalone view. I'll try it with `AXEmojiView` 👍

**Comment by dbreskvar** [comment]
Works perfectly without using the EmojiPopupLayout, thanks 💪
