### ISSUE TITLE
some small question : hide pager titleView/ sticker keyboard does not show full screen

### ISSUE THREAD

**Issue by fukemy** [Aghajari/AXEmojiView#4]
Hi, first thanks you very much for great library, it's help me a lot about using custom gif as emoji keyboard. I totally done with your library, but i still have some question below.

 1. I just want to show my custom gif page only, so i dont need page TitleView, so can you give me some advice to hide it?
 2. When show gif keyboard, i saw the last row is not display totally, as the video i uploaded, please help

https://streamable.com/7qbea2 ( the video i just uploading, may be it's need a bit of time to show)

**Comment by Aghajari** [comment]
Hi @fukemy ,
Are you using StickerView for your GIF page?

Create a new View extends AXEmojiLayout or AXEmojiBase  (Just like LoadingView in app sample)
And add a RecyclerView to this view.

final step, load your GIFs in the RecyclerView and add this view as a page to the AXEmojiPager...

**Comment by fukemy** [comment]
Yes i want to using StickerView for GIF page only, let me check your advices thanks

**Comment by Aghajari** [comment]
Hi @fukemy ,
check out AXEmojiView version 1.2.1
you can disable Category with this line : (add this when you are setting the EmojiView theme)
```java
AXEmojiManager.getStickerViewTheme().setCategoryEnabled(false);
```

and also if you couldn't see the last row completely (only if you are using customView), you should add an ItemDecoration to your RecyclerView, just like this :
```java
recyclerView.addItemDecoration(Utils.getRVLastRowBottomMarginDecoration(Utils.dp(this,40)));
```
Keep me updated. 😄

**Comment by fukemy** [comment]
hello, thanks for your helping, i really busy in webrtc android, it's terrible, i swear i will update post ASAP, i will return in few days( next week)
