### ISSUE TITLE
EmojiSize

### ISSUE THREAD

**Issue by ramvdixit** [Aghajari/AXEmojiView#6]
Awesome library! I have one issue though. I want to find out if the text contains only emojis and then assign a size to the emoji(s). If its a single emoji, it should be 40sp and if multiple emojis, it should be 30sp. If the text has a combination of text and emojis, the default size is preserved. But the first two conditions cut the emojis in half and are not fully visible. Any pointers, please? Attached is a screen shot.

![Screenshot_20200916-195217](https://user-images.githubusercontent.com/5763122/93350424-42370780-f856-11ea-8830-9af697be8f80.png)

Please note, "messageContent" is an AXEmojiTextView 

```
if (EmojiUtils.isOnlyEmojis(content) {
                    if (EmojiUtils.emojisCount(content) == 1) {
                        messageContent.setEmojiSizeRes(R.dimen.emoji_size_single_emoji, false); // 40sp
                    } else {
                        messageContent.setEmojiSizeRes(R.dimen.emoji_size_only_emojis, false); // 30sp
                    }
                    messageContent.setText2(content);
                } else {
                    messageContent.setEmojiSizeRes(R.dimen.emoji_size_default); // 20sp
                    messageContent.setText2(content);
                }
}
```

**Comment by Aghajari** [comment]
Hi @ramvdixit ,
Change the TextView textSize too (change both emojiSize and textSize)

_Note: i usually set textSize 2dp less than emojiSize_

**Comment by ramvdixit** [comment]
That was super fast! Thank you. I will try that and post back of what I find. Thank you very much and good luck.

**Comment by ramvdixit** [comment]
Changing the text size to accommodate "Single Only Emojis" and "Multiple Emojis Only" works perfectly! Thank you. Keep up the good work again!
