### ISSUE TITLE
How to display stickers?

### ISSUE THREAD

**Issue by fiftyonemoon** [Aghajari/AXEmojiView#7]
Hey Amir,
Your library is really good. can you please tell me how to display stickers? as in your demo app when we clicked on sticker it's show toast. onClickMethod have 3 params but how to use them?

**Comment by Aghajari** [comment]
Hi @fiftyonemoon ,
i think i didn't understand what you mean,
actually it won't show a toast when you click on sticker tab, it will open the Stickers tab by default...

I need more details about what you wanna do..

**Comment by fiftyonemoon** [comment]
[https://firebasestorage.googleapis.com/v0/b/twish-chat.appspot.com/o/WhatsApp%20Image%202020-10-16%20at%203.38.49%20PM.jpeg?alt=media&token=573dc2ef-b6f5-4682-acee-c64c490256bb](url)

see in this image. how to display it in chat?

**Comment by Aghajari** [comment]
Aha! 
you must add an ImageView to your layout (RecyclerView) and load your sticker resource on it!

**Comment by fiftyonemoon** [comment]
Yaa but see this!

stickerView.setOnStickerActionsListener(new OnStickerActions() {
                @Override
                public void onClick(View view, Sticker sticker, boolean fromRecent) {
                    Toast.makeText(view.getContext(),sticker.toString()+" clicked!", Toast.LENGTH_SHORT).show();
                }

                @Override
                public boolean onLongClick(View view, Sticker sticker, boolean fromRecent) {
                    return false;
                }
            });

Here onClickMehtod have 3 parmas but how to load in imageview? I tried but nothing happened.
By the way response time is great.

**Comment by fiftyonemoon** [comment]
Ok Amir.
I solved it by just adding imageView.setImageResource((int) Sticker.tostirng()); 
Thank you.

**Comment by Aghajari** [comment]
Well done!
Note: it's better to use getData instead of toString, `imageView.setImageResource((int) sticker.getData());`

**Comment by fiftyonemoon** [comment]
Ok Amir. 
Can i text you on Telegram in future? if i need some help?
TelegramID : @KingAmir272 is it yours?

**Comment by Aghajari** [comment]
Yes sure,
Just mention this conversation :D

**Comment by fiftyonemoon** [comment]
Getting this type of error

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at com.fom.emoji_stickers.shared.RecentEmojiManager.<init>(RecentEmojiManager.java:71)
        at com.fom.emoji_stickers.AXEmojiManager.getRecentEmoji(AXEmojiManager.java:477)
        at com.fom.emoji_stickers.view.AXEmojiView.init(AXEmojiView.java:153)
        at com.fom.emoji_stickers.view.AXEmojiView.<init>(AXEmojiView.java:46)
        at com.app.twishchat.sticker.UI.loadView(UI.java:48)
        at com.app.twishchat.ESActivity.onCreate(ESActivity.java:47)
        at android.app.Activity.performCreate(Activity.java:6093)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)


EROOR POINT:

public RecentEmojiManager(@NonNull final Context context) {
        this.context = context.getApplicationContext();
        reload();
    }
