### ISSUE TITLE
Not working with androidx

### ISSUE THREAD

**Issue by Kautuk46** [Aghajari/AXEmojiView#9]
When creating the object of AXEmojiView, a "NoClassDefFoundError" is thrown:

java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/recyclerview/widget/RecyclerView$OnScrollListener;

**Comment by Aghajari** [comment]
Hi,
Implementing recyclerview should fix this issue.

```gradle
implementation 'androidx.recyclerview:recyclerview:1.2.0-alpha05'
```

**Comment by Kautuk46** [comment]
Got it to work. 
Thanks 👍
